Repository richardltyler/GitFit, pull requests merged in 2020-12, with the labels that each got.

#19 Update feature_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#20 Remove checklist in pr template
  docs/pull_request_template.md
Labels: documentation

#12 Finish 'user info' section in dashboard
  src/index.html
  src/scripts.js
Labels: enhancement

#13 Testing/hydration-log
  test/Hydration-test.js
Labels: testing

#23 Feature/flexbox styling
  src/index.html
  src/styles.css
Labels: enhancement

#24 Build HydrationLog class and pass all tests
  src/HydrationLog.js
  test/HydrationLog-test.js
Labels: enhancement, testing

#27 Testing/sleep-repository
  test/SleepRepository-test.js
Labels: testing

#21 Testing/activity-repository
  test/ActivityRepository-test.js
Labels: testing

#39 Feature/activity repo
  src/ActivityRepository.js
  test/ActivityRepository-test.js
Labels: enhancement

#29 Feature/sleep-repository-and-log
  src/SleepLog.js
  src/SleepRepository.js
  src/User.js
  src/UserRepository.js
  src/index.html
  test/SleepRepository-test.js
Labels: enhancement

#41 Build test for SleepLog class and pass tests
  src/SleepLog.js
  src/User.js
  test/SleepLog-test.js
Labels: enhancement, testing

#43 Testing/activity-log
  test/ActivityLog-test.js
  test/ActivityRepository-test.js
Labels: testing

#50 Feature/activity log
  src/ActivityLog.js
  src/User.js
  test/ActivityLog-test.js
Labels: enhancement

#52 Feature/charts
  package-lock.json
  package.json
  src/HydrationLog.js
  src/SleepLog.js
  src/SleepRepository.js
  src/User.js
  src/UserRepository.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#51 Refactor/architecture
  src/ActivityLog.js
  src/HydrationLog.js
  src/SleepLog.js
  src/User.js
  src/WellnessLog.js
  src/index.html
  src/scripts.js
  test/ActivityLog-test.js
  test/HydrationLog-test.js
  test/SleepLog-test.js
  test/WellnessLog-test.js
Labels: refactor, testing

#61 Feature/update charts
  src/chart-drafts.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#62 Finetune widget organization and colors
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement, refactor

#64 Update README
  README.md
Labels: documentation

#67 Feature/display rankings
  src/ActivityRepository.js
  src/UserRepository.js
  src/WellnessLog.js
  src/chart-drafts.js
  src/charts.js
  src/index.html
  src/scripts.js
Labels: enhancement

#71 Feature/complete data display
  src/ActivityRepository.js
  src/charts.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#73 Feature/responsiveness
  src/index.html
  src/styles.css
Labels: enhancement

#83 Refactor/chartjs filepath
  src/index.html
Labels: bug, enhancement

#86 Finalize README
  README.md
Labels: documentation

#87 Fix/responsive texts
  src/charts.js
  src/index.html
  src/scripts.js
Labels: bug

#102 Refactor/user repo
  src/User.js
  src/UserRepository.js
  src/WellnessLog.js
  src/scripts.js
  test/User-test.js
  test/UserRepository-test.js
  test/WellnessLog-test.js
Labels: enhancement, refactor, testing

#105 Refactor/activity repository
  src/ActivityRepository.js
  test/ActivityRepository-test.js
Labels: refactor

#103 Refactor/sleep repository
  src/SleepRepository.js
  src/WellnessLog.js
  test/SleepRepository-test.js
Labels: refactor

#104 Refactor charts
  src/charts.js
  src/scripts.js
Labels: refactor

#106 Refactor/wellness logs
  src/User.js
  src/UserRepository.js
  src/WellnessLog.js
  test/WellnessLog-test.js
Labels: enhancement, refactor

#107 Refactor/design
  src/index.html
  src/styles.css
Labels: enhancement, refactor

#108 Refactor/scripts
  src/scripts.js
Labels: enhancement, refactor

#88 Update README.md
  README.md
Labels: documentation
